{
    [
        "When there is no desire, all things are at peace. - Laozi",
        "Simplicity is the ultimate sophistication. - Leonardo da Vinci",
        "Simplicity is the essence of happiness. - Cedric Bledsoe",
        "Smile, breathe, and go slowly. - Thich Nhat Hanh",
        "Simplicity is an acquired taste. - Katharine Gerould",
        "Well begun is half done. - Aristotle",
        "He who is contented is rich. - Laozi",
        "Very little is needed to make a happy life. - Marcus Antoninus",
        "It is quality rather than quantity that matters. - Lucius Annaeus Seneca",
        "Genius is one percent inspiration and ninety-nine percent perspiration. - Thomas Edison",
        "Computer science is no more about computers than astronomy is about telescopes. - Edsger Dijkstra",
        "It always seems impossible until it is done. - Nelson Mandela",
        "Act only according to that maxim whereby you can, at the same time, will that it should become a universal law. - Immanuel Kant",
        "Simplicity is the ultimate sophistication. - Leonardo da Vinci",
        "Success is going from failure to failure without losing your enthusiasm. - Winston Churchill",
        "The journey of a thousand miles begins with one step. - Lao Tzu",
        "Dream big and dare to fail. - Norman Vaughan",
        "The power of imagination makes us infinite. - John Muir",
        "Make each day your masterpiece. - John Wooden",
        "Believe and act as if it were impossible to fail. - Charles Kettering",
        "Light tomorrow with today. - Elizabeth Barrett Browning",
        "Even if you're on the right track, you'll get run over if you just sit there. - Will Rogers",
        "Believe you can and you're halfway there. - Theodore Roosevelt",
        "Don't wait. The time will never be just right. - Napoleon Hill",
        "A year from now you may wish you had started today. - Karen Lamb",
        "It is never too late to be what you might have been. - George Eliot",
        "If there is no struggle, there is no progress. - Frederick Douglass",
        "What we fear doing most is usually what we most need to do. - Tim Ferriss",
        "Do what you love and the money will follow. - Marsha Sinetar",
        "Champions keep playing until they get it right. - Billie Jean King",
        "Action is the foundational key to all success. - Pablo Picasso"
    ];
}
